server:
  port: 8080
  servlet:
    context-path: /api


spring:
  application:
    name: supra

  datasource:
    url: jdbc:postgresql://localhost:5432/supra_db
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  key: XRkKb8YZ7/GUfg21l6gGDuNOtEE4mc2phsK7U7DV1agZw07ejwyRQkoVJ7Yl/TYz